name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
    
env:
  PULUMI_VERSION: 3.201.0

jobs:
  bulid:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Setup Pulumi CLI
      uses: pulumi/actions@v6.2.0
      with:
        pulumi-version: ${{ env.PULUMI_VERSION }}        
    - name: Build
      run: |
        pulumi package gen-sdk --language dotnet .
        dotnet build
